### ISSUE TITLE
TVirtualExplorerTreeview crash if Active := True

### ISSUE THREAD

**Issue by olegchensky** [TurboPack/MustangpeakVirtualshellTools#10]
Hi. It is really not possible to use the last version.

Design- and RunTime are the same.
Last Studio with all Hotfixes. Last sources.

**Comment by pat-mar** [comment]
Hello,

I'm facing the same issue...

Moving an older project to Delphi Rio. Installed the latest version from here. Couldn't open a .dfm file in Delphi, because it crashed on attempt. Figured out at some point, that it was because a TVirtualExplorerTreeview control was saved with Active property set to true, which worked fine before.

Modified the .dfm file and set Active to false and was able to open the unit / form in Delphi now.

Tried to set Active to true in the object inspector -> Delphi crash again.

Compared this form to some similar and found out, that RootFolder was set to "rfDesktop" in this case, while it was "rfCustom" in other cases, so set it to "rfCustom" here as well and was able to set Active to true in the object inspector now. However, when launching the application and accessing that form at run time, it crashes.

When I leave Active at false and try to set it to true at run time, again it crashes, so something is broken here...

Any chance for a fix?

**Comment by AlekseyRykov2018** [comment]
I have this problem too. 
Work fine (10.3.2 Rio) only with VirtualTreeview 7.1, if use latest VirtualTreeview 7.2 or 7.3 ->  crash on Active := True;
As temporary solution - use VTV 7.1 https://github.com/Virtual-TreeView/Virtual-TreeView/tree/7.1.0

**Comment by olegchensky** [comment]
No changes... I go to JAM Software.

**Comment by olegchensky** [comment]
Now works with the last VirtualTreeView Update.

**Comment by krundt** [comment]
Installed everything today on fresh Delphi 10.4 and have the same original problem: Delphi freezes and shuts down when setting Active to True for a VirtualExplorerTree or -TreeView. All other controls seem to work. I have VirtualTreeView V7.3: (04 Nov 2019) installed. It is supposed to be the latest. But is says "Updated for 10.3 Rio / VER330 / PKG 260" so probably no support for 10.4, then.

**Comment by krundt** [comment]
Tried the VirtualTreeView from JAM software which claims to be V 7.4 and support 10.4 Maybe it does, but it didn't help at all. Pity...

**Comment by adrienreboisson** [comment]
Same problem here.

**Comment by pyscripter** [comment]
Please try with the current code base.  This should have been fixed.  Reopen the issue if the problem still exists.
